name: Django CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.9]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install -r requirements-testing.txt
    - name: Run Tests
      run: |
        python manage.py test
    - name: Run flake8
      uses: suo/flake8-github-action@releases/v1
      with:
        checkName: 'flake8_py3'   # NOTE: this needs to be the same as the job name
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
